Changed the http status code from 500 Internal Server Error to 504 Gateway Timeout after timing out from the backend
googlecloudrobotics/core pull request #227
Opened 2023-09-16 01:25 UTC by theaimboy

Testedt by using curl through a relay-server to a slow backend, and seeing the relay-server responding with a "HTTP/2 504" error instead of 500 and "Timeout after 1m0s, indicating that the backend request took too long" in the body.

2023-09-18 07:29 UTC, hauke76 requested changes
Can you please add a test which shows that we hit this branch after the timeout? Since now both the relay server and client are separate classes, it is possible to write such a test without the need to start multiple binaries for the client/server.

2023-09-18 10:46 UTC, hauke76 approved these changes

2023-09-18 10:47 UTC, hauke76 commented
To unblock us in landing this change and the reverse proxy change, I unblocked the submission here despite the missing test. I will add an issue which tracks the test implementation.

2023-09-18 10:50 UTC, hauke76 commented
Added https://github.com/googlecloudrobotics/core/issues/229 to track the implementation of the test.

2023-09-21 16:35 UTC, drigz commented
#230

2023-09-21 16:35 UTC, closed without merging